version: '3.2'
services:

  logstash:
    container_name: logstash
    hostname: logstash
    image: docker.elastic.co/logstash/logstash:7.6.2
    ports:
      - "5000:5000/tcp"
      - "5000:5000/udp"
      - "9600:9600"
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    volumes:
      - type: bind
        source: ./logstash/config/logstash.yml
        target: /usr/share/logstash/config/logstash.yml
        read_only: true
      - type: bind
        source: ./logstash/pipeline/logstash.conf
        target: /usr/share/logstash/pipeline/logstash.conf
        read_only: true
      - type: bind
        source: ./logstash/pem
        target: /usr/share/logstash/pem
        read_only: true
      - type: bind
        source: ./logstash/logs
        target: /usr/share/logstash/logs
        read_only: true
      - type: bind
        source: ./logstash/utilities
        target: /usr/share/logstash/utilities
        read_only: true
      - type: bind
        source: ./logstash/ssl
        target: /usr/share/logstash/ssl
        read_only: true
    extra_hosts:
      - "ILOG376NP0511.americas.hpqcorp.net:16.91.158.182"

  zookeeper:
    container_name: zookeeper
    hostname: zookeeper
    image: wurstmeister/zookeeper:latest
    ports:
      - "2181:2181"

  kafka:
    container_name: kafka
    hostname: kafka
    image: wurstmeister/kafka:latest
    ports:
      - "9092:9092"
      - "9093:9093"
      - "9094:9094"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://kafka:9092,SSL://kafka:9093"
      KAFKA_LISTENERS: "PLAINTEXT://kafka:9092,SSL://kafka:9093"
      KAFKA_CREATE_TOPICS: "tampa-collector:1:1,tampa-listener:1:1,tampa-utilities:1:1,tampa-n3000:1:1,tampa-logs:1:1"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    links:
      - zookeeper
    depends_on:
      - zookeeper

  kafdrop:
    container_name: kafdrop
    hostname: kafdrop
    image: obsidiandynamics/kafdrop
    ports:
      - "9000:9000"
    environment:
      KAFKA_BROKERCONNECT: "kafka:9092"
      JVM_OPTS: "-Xms1024M -Xmx1024M -Xss180K -XX:-TieredCompilation -XX:+UseStringDeduplication -noverify"
    depends_on:
      - "kafka"

